theme: jekyll-theme-minimal
title: DynaMimicGen (D-MG)
description: Website of the project <a href="https://arxiv.org/abs/2511.16223">(DynaMimicGen)</a>: A Data Generation Framework for Robot Learning of Dynamic Tasks
